version: '3'
services:
  api:
    build: .
    ports:
      - 3001:3000
    volumes: 
      - .:/opt/api
    links: 
      - mongo
    environment: 
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - DB_NAME=todo
      - NODE_ENV=development
      - PORT=3000
  mongo:
    image: mongo:3.0.15